/*
@TargetNode='localhost'
@GeneratedBy=jon.clyde
@GenerationDate=02/19/2020 14:04:43
@GenerationHost=DESKTOP-287BQAS
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
SourceInfo = "::10::9::WindowsFeature";
 ModuleName = "PsDesiredStateConfiguration";
 Ensure = "Present";
 ResourceID = "[WindowsFeature]RSATTools";
 IncludeAllSubFeature = True;
 Name = "RSAT-AD-Tools";

ModuleVersion = "1.0";
 ConfigurationName = "RSATFeature";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";
 
                        MinimumCompatibleVersion = "1.0.0";
 
                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 
                        Author="jon.clyde";
 
                        GenerationDate="02/19/2020 14:04:43";
 
                        GenerationHost="DESKTOP-287BQAS";
 
                        Name="RSATFeature";

                    };
